gateway:
  routes:
    - id: A1-Policy
      uri: https://policymanagementservice.nonrtric:9081
      predicates:
        - Path=/a1-policy
    - id: A1-EI
      uri: https://informationservice.nonrtric:9083
      predicates:
        - Path=/data-producer
        - Path=/data-consumer
    # - id: Test
    #   uri: https://localhost:8080
    #   predicates:
    #     - Path=/hello
    #     - Path=/hello
    - id: HttpTest
      uri: http://192.168.122.203:50123
      predicates:
        - Path=/httphello
        - Path=/httphello