gateway:
  routes:
    - id: A1-Policy
      uri: https://policymanagementservice:9081
      predicates:
        - Path=/a1-policy
    - id: A1-EI
      uri: https://informationservice:9083
      predicates:
        - Path=/data-producer
        - Path=/data-consumer
    - id: Test
      uri: https://localhost:8080
      predicates:
        - Path=/hello/
    - id: HttpTest
      uri: http://localhost:50123
      predicates:
        - Path=/httphello/